// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9FlZaIFyw6Twe_HOwByb4yKn66xLdMvM',
    appId: '1:832435712282:web:06d444eefb04450a34bca3',
    messagingSenderId: '832435712282',
    projectId: 'quizify-proyek-mmp',
    authDomain: 'quizify-proyek-mmp.firebaseapp.com',
    storageBucket: 'quizify-proyek-mmp.firebasestorage.app',
    measurementId: 'G-VQGMW0X0JH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAExYeZF2kfkkGTTrevMBJS7hesXlAN_Zw',
    appId: '1:832435712282:android:bfcd7dc4522645be34bca3',
    messagingSenderId: '832435712282',
    projectId: 'quizify-proyek-mmp',
    storageBucket: 'quizify-proyek-mmp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVAK0iJsRC1yVOtrAO_Dl_RMOEkP4VH2s',
    appId: '1:832435712282:ios:9cfe11f944f9089434bca3',
    messagingSenderId: '832435712282',
    projectId: 'quizify-proyek-mmp',
    storageBucket: 'quizify-proyek-mmp.firebasestorage.app',
    iosBundleId: 'io.github.celoxe11.quizify.quizifyProyekMmp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVAK0iJsRC1yVOtrAO_Dl_RMOEkP4VH2s',
    appId: '1:832435712282:ios:9cfe11f944f9089434bca3',
    messagingSenderId: '832435712282',
    projectId: 'quizify-proyek-mmp',
    storageBucket: 'quizify-proyek-mmp.firebasestorage.app',
    iosBundleId: 'io.github.celoxe11.quizify.quizifyProyekMmp',
  );
}
